version: "3.9"

services:
  receipts-service:
    build: .
    container_name: receipts-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MONGODB_URI=${MONGODB_URI:-mongodb://localhost:27017/receipts}
      - MONGODB_DATABASE=Receipts
    networks:
      - eciexpress-network

networks:
  eciexpress-network:
    driver: bridge
